# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

# URL is the base hostname with protocol for your site, eg http://example.com
url: "https://edoardotosin.com" # the base hostname & protocol for your site, e.g. http://example.com

domain_url: https://edoardotosin.com # Custom variable. Same value as url but doesn't change when debugging to 127.0.0.1

# If you want to install this jekyll in a subpath (eg /digitalgarden) set it here.
# Else keep it Empty (DON'T PUT /; Keep it empty)
baseurl: "/tools"

# Website Header, Description, Footer year and text.
# If you are deleting this, make sure you remove it from HTML files too
title: Edoardo Tosin
heading: Edoardo Tosin # Change this
content: "CS Odyssey: Tech Insights & Adventures"
description: "Welcome aboard to the computer science playground! I'm thrilled to have you here as we embark on this digital adventure together. My name is Edoardo Tosin, and I am a passionate coder and tech enthusiast, deeply immersed in the world of computer science. Here you will find a collection of my explorations across various domains, primarily focusing on computer science but also venturing into other intriguing realms that spark my curiosity. These are my digital footprints, documenting the insights, learnings, and cool stuff I come across in the ever-evolving field of computer science and beyond."
author: Edoardo Tosin
link:
    license: "https://creativecommons.org/licenses/by/4.0/"
    mastodon:
        - "https://mastodon.social/@edoardotosin"
        - "https://infosec.exchange/@EdoardoTosin"
    bluesky: "https://bsky.app/profile/edoardotosin.com"
    github: "https://github.com/edoardotosin"
    flickr: "https://www.flickr.com/photos/edoardo_tosin/"
copyright:
  year: 2022
  msg: Contents under CC BY 4.0

twitter: EdoardoTosin

ogimg: "/assets/img/OGImg.jpg"

timezone: Europe/Rome

lang: en

feed:
  icon: /assets/img/favicon.png
  posts_limit: 50

# Set title and content for private & broken link tooltop
privatelinks:
  title: Private or Broken Links
  msg: The page you're looking for is either not available or private!

# Theme level preferences
# To enable set "enabled : true" else, use "enabled:false"
preferences:
  search:
    enabled: true
  wiki_style_link:
    enabled: true
  pagepreview:
    enabled: true
  backlinks:
    enabled: false
    notes:
      enabled: true
    pages:
      enabled: false
# To enable a homepage, change the value to true and add content to _includes/Homepage.html
# If enable : false, notes feed will be as homepage.
  homepage:
    enabled: true ##If you need a homepage, change this to true and edit _includes/Homepage.html
  related:
    enabled: true

encoding: utf-8

# Build settings
theme: null
plugins:
  - jekyll-spaceship

## Enable Collections
collections:
    script:
      output: true
      permalink: /:name

markdown: kramdown

kramdown:
  input: GFM
  hard_wrap: false
  math_engine: katex
  smart_quotes: ["apos", "apos", "quot", "quot"]
  syntax_highlighter: rouge

sass:
  style: compressed

defaults:
  - scope:
      path: "_script/"
    values:
      layout: none
      permalink: /:name

exclude:
  - .github
  - .gitattributes
  - .gitignore
  - README.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - SECURITY.md
  - LICENSE
  - tools
  - debug.yml
  - debug.sh
  - docker-compose.yml
  - _script/*.md
  - SCRIPT_CATALOG.md
  - Dockerfile
  - docker-compose.yml
